### ISSUE TITLE
Program doesn't work.

### ISSUE THREAD

**Issue by lkellar** [puffyboa/FLAPBIRD#1]
After installing and running program, I got this error.
 ![error message](https://user-images.githubusercontent.com/28833934/29393857-14707352-82cc-11e7-8fed-2a21080d23f1.png)

**Comment by jpsank** [comment]
Aww it looks like it doesn't work on TI-84 Plus CE, I'll have to add that to the readme when I get my computer

**Comment by lkellar** [comment]
:(
